apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "simple-cnn"
spec:
  predictor:
    canaryTrafficPercent: 50
    tensorflow:
      storageUri: "pvc://simple-cnn-pvc2/"   
