apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-cnn-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-cnn-copy-job
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-writer
        image: tomas/simple-cnn-copy:1.0
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          echo ">>> Creating version directory...";
          mkdir -p /mnt/models/1;
          echo ">>> Copying model to PVC...";
          cp -r /app/model/* /mnt/models/1/;
          echo ">>> Verifying contents in PVC...";
          ls -lh /mnt/models/1;
          echo ">>> Verification complete. Job finished.";
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: simple-cnn-pvc
