apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-cnn-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
######################
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-cnn-copy-job
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-writer
        # La tua immagine pubblica su Docker Hub
        image: tomasconti02/simple-cnn-copy:1.0
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          mkdir -p /mnt/models/1;
          cp -r /app/model/* /mnt/models/1/;
          ls -lh /mnt/models/1;
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: simple-cnn-pvc
