apiVersion: batch/v1
kind: Job
metadata:
  name: simple-cnn-copy-job-v2
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: model-writer
        image: tomasconti02/simple-cnn-copy:1.1 # Immagine specifica per la v1.1
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          mkdir -p /mnt/models/2; # Creiamo la cartella per la versione 2
          cp -r /app/model/* /mnt/models/2/;
          ls -lh /mnt/models/2;
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: simple-cnn-pvc
