apiVersion: v1
kind: Pod
metadata:
  name: python-minio-test
  namespace: drift-system
spec:
  containers:
  - name: python
    image: python:3.9-slim
    command: ["/bin/sh", "-c"]
    args:
      - |
        pip install boto3 minio Pillow &&
        echo "Librerie installate. Il pod rimane in esecuzione per consentire test interattivi." &&
        sleep infinity
    env:
    - name: MINIO_ENDPOINT
      value: "minio.drift-system.svc.cluster.local:9000"
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_ROOT_USER
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_ROOT_PASSWORD
    - name: MINIO_SECURE
      value: "False"   # perché usiamo HTTP (non HTTPS)
  restartPolicy: Never
