apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: drift-system
spec:
  serviceName: qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-storage
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
